list/urls.py
from django.urls import path

from list.views import (
    TaskListView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    TagListView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView, task_ready_or_not,
)

urlpatterns = [
    path(
        "",
        TaskListView.as_view(),
        name="task-list",
    ),
    path(
        "task/create/",
        TaskCreateView.as_view(),
        name="task-create",
    ),
    path(
        "task/<int:pk>/update/",
        TaskUpdateView.as_view(),
        name="task-update",
    ),
    path(
        "task/<int:pk>/task-ready-or-not/",
        task_ready_or_not,
        name="task-ready-or-not",
    ),
    path(
        "task/<int:pk>/delete/",
        TaskDeleteView.as_view(),
        name="task-delete",
    ),
    path(
        "tags/",
        TagListView.as_view(),
        name="tag-list",
    ),
    path(
        "tag/create/",
        TagCreateView.as_view(),
        name="tag-create",
    ),
    path(
        "tag/<int:pk>/update/",
        TagUpdateView.as_view(),
        name="tag-update",
    ),
    path(
        "tag/<int:pk>/delete/",
        TagDeleteView.as_view(),
        name="tag-delete",
    ),
]

app_name = "todo_list"

todo_list/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("list.urls", namespace="todo_list")),
]

list/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=255, unique=True)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Task(models.Model):
    content = models.CharField(max_length=255)
    datetime = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(blank=True, null=True)
    ready_or_not = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag, related_name="tasks")

    class Meta:
        ordering = ["id"]

    def __str__(self):
        return self.content

list/forms.py
from django import forms

from list.models import Tag, Task


class TaskForm(forms.ModelForm):
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )
    deadline = forms.DateTimeField(required=False)

    class Meta:
        model = Task
        fields = ["content", "deadline", "tags"]

list/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic

from list.forms import TaskForm
from list.models import Tag, Task


def index(request):
    """View function for the home page of the site."""

    return render(request, "list/task_list.html")


class TaskListView(generic.ListView):
    model = Task
    paginate_by = 5


class TaskCreateView(generic.CreateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("todo_list:task-list")


class TaskUpdateView(generic.UpdateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("todo_list:task-list")


class TaskDeleteView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy("todo_list:task-list")


class TagListView(generic.ListView):
    model = Tag
    paginate_by = 5


class TagCreateView(generic.CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo_list:tag-list")


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo_list:tag-list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("todo_list:tag-list")


def task_ready_or_not(request, pk=None):
    if request.method == "POST" and pk is not None:
        task = Task.objects.get(pk=pk)
        task.ready_or_not = not task.ready_or_not
        task.save()
    return redirect("todo_list:task-list")

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block title %}<title>ToDo list</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
          crossorigin="anonymous">
    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2">

            {% block sidebar %}
                {% include "includes/sidebar.html" %}
            {% endblock %}

        </div>
        <div class="col-sm-10 ">

            {% block content %}{% endblock %}

            {% block pagination %}
                {% include "includes/pagination.html" %}
            {% endblock %}

        </div>
    </div>
</div>
</body>

</html>


templates/includes/pagination.html
{% load query_transform %}

{% if is_paginated %}
  <ul class="pagination">

    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.previous_page_number %}" class="page-link">prev</a>
      </li>
    {% endif %}

    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>

    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.next_page_number %}" class="page-link">next</a>
      </li>
    {% endif %}

  </ul>
{% endif %}

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <br>
  <li class="list-group-item"><a href="{% url 'todo_list:task-list' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'todo_list:tag-list' %}">Tag list</a></li>

</ul>

templates/list/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete tag {{ tag.name }}?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/list/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} tag</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/list/tag_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <br>
  <div>
    <h1>Tags list
      <a href="{% url 'todo_list:tag-create' %}" class="btn btn-success">
        Create
      </a>
    </h1>
  </div>


   {% if tag_list %}
    <table class="table">
      <tr>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>

      {% for tag in tag_list %}
        <tr>
          <td>
              {{ tag.name }}
          </td>
          <td>
              <a href="{% url 'todo_list:tag-update' pk=tag.id %}" class="btn btn-warning">
                &#9881;
              </a>
            </td>
            <td>
              <a href="{% url 'todo_list:tag-delete' pk=tag.id %}" class="btn btn-danger">
                🗑️
              </a>
            </td>
        </tr>
      {% endfor %}
    </table>
   {% else %}
      <p>There are no tags.</p>
   {% endif %}
{% endblock %}

templates/list/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete task {{ task.content }}?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <a href="{% url 'todo_list:task-list' %}" class="btn btn-success">No</a>
  </form>
{% endblock %}

templates/list/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} task</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/list/task_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}


{% block content %}
  <br>
  <div>
    <h1>TODO list &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      <a href="{% url 'todo_list:task-create' %}" class="btn btn-primary link-to-page">
        add task
      </a>
    </h1>
  </div>

  {% if task_list %}
    <ol>
      {% for task in task_list %}
        <li class="list-group-item">
          <h3>
            <strong>{{ task.content }}</strong>
            {% if task.ready_or_not %}
              <text style="color: green"> Done</text>
            {% else %}
              <text style="color: red">Not Done</text>
            {% endif %}
          </h3>
          <div class="coll-2">
            <form action="{% url 'todo_list:task-ready-or-not' pk=task.id %}" method="post">
              {% csrf_token %}
              {% if task.ready_or_not %}
                <button type="submit" class="btn btn-secondary btn-lg float-right">Undo</button>
              {% else %}
                <button type="submit" class="btn btn-success btn-lg float-right">Complete</button>
              {% endif %}
            </form>
          </div>
          <p>Created: {{ task.datetime }} &nbsp;&nbsp;&nbsp;&nbsp;
            {% if task.deadline %}
              Deadline: {{ task.deadline }}</p>
            {% endif %}
          <p>Tags:
            {% for tag in task.tags.all %}
              {{ tag.name }}
            {% endfor %}
            <a href="{% url 'todo_list:task-update' pk=task.id %}">
              Update
            </a>
            <a href="{% url 'todo_list:task-delete' pk=task.id %}">
              Delete
            </a>
          </p>
        </li>
      {% endfor %}
    </ol>
  {% else %}
    <p>There are no tasks</p>
  {% endif %}

{% endblock %}
